// <auto-generated />
using System;
using ApiParchePlanU.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiParchePlanU.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260520220712_AddCreatorIdToParche")]
    partial class AddCreatorIdToParche
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiParchePlanU.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("Attendances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PlanId = 1,
                            Status = 0,
                            UserId = "user-0001"
                        },
                        new
                        {
                            Id = 2,
                            PlanId = 1,
                            Status = 0,
                            UserId = "user-0002"
                        },
                        new
                        {
                            Id = 3,
                            PlanId = 1,
                            Status = 2,
                            UserId = "user-0003"
                        },
                        new
                        {
                            Id = 4,
                            PlanId = 2,
                            Status = 0,
                            UserId = "user-0004"
                        },
                        new
                        {
                            Id = 5,
                            PlanId = 2,
                            Status = 1,
                            UserId = "user-0005"
                        },
                        new
                        {
                            Id = 6,
                            PlanId = 2,
                            Status = 0,
                            UserId = "user-0001"
                        },
                        new
                        {
                            Id = 7,
                            PlanId = 3,
                            Status = 2,
                            UserId = "user-0002"
                        },
                        new
                        {
                            Id = 8,
                            PlanId = 3,
                            Status = 0,
                            UserId = "user-0003"
                        },
                        new
                        {
                            Id = 9,
                            PlanId = 4,
                            Status = 0,
                            UserId = "user-0004"
                        },
                        new
                        {
                            Id = 10,
                            PlanId = 4,
                            Status = 0,
                            UserId = "user-0005"
                        },
                        new
                        {
                            Id = 11,
                            PlanId = 5,
                            Status = 1,
                            UserId = "user-0001"
                        },
                        new
                        {
                            Id = 12,
                            PlanId = 5,
                            Status = 0,
                            UserId = "user-0002"
                        },
                        new
                        {
                            Id = 13,
                            PlanId = 6,
                            Status = 0,
                            UserId = "user-0003"
                        },
                        new
                        {
                            Id = 14,
                            PlanId = 6,
                            Status = 2,
                            UserId = "user-0004"
                        },
                        new
                        {
                            Id = 15,
                            PlanId = 7,
                            Status = 0,
                            UserId = "user-0005"
                        },
                        new
                        {
                            Id = 16,
                            PlanId = 7,
                            Status = 0,
                            UserId = "user-0001"
                        },
                        new
                        {
                            Id = 17,
                            PlanId = 8,
                            Status = 1,
                            UserId = "user-0002"
                        },
                        new
                        {
                            Id = 18,
                            PlanId = 8,
                            Status = 0,
                            UserId = "user-0003"
                        },
                        new
                        {
                            Id = 19,
                            PlanId = 1,
                            Status = 0,
                            UserId = "user-0004"
                        },
                        new
                        {
                            Id = 20,
                            PlanId = 1,
                            Status = 2,
                            UserId = "user-0005"
                        },
                        new
                        {
                            Id = 21,
                            PlanId = 9,
                            Status = 0,
                            UserId = "user-0006"
                        },
                        new
                        {
                            Id = 22,
                            PlanId = 9,
                            Status = 0,
                            UserId = "user-0007"
                        },
                        new
                        {
                            Id = 23,
                            PlanId = 9,
                            Status = 2,
                            UserId = "user-0008"
                        },
                        new
                        {
                            Id = 24,
                            PlanId = 10,
                            Status = 0,
                            UserId = "user-0009"
                        },
                        new
                        {
                            Id = 25,
                            PlanId = 10,
                            Status = 1,
                            UserId = "user-0010"
                        },
                        new
                        {
                            Id = 26,
                            PlanId = 10,
                            Status = 0,
                            UserId = "user-0006"
                        },
                        new
                        {
                            Id = 27,
                            PlanId = 11,
                            Status = 2,
                            UserId = "user-0007"
                        },
                        new
                        {
                            Id = 28,
                            PlanId = 11,
                            Status = 0,
                            UserId = "user-0008"
                        },
                        new
                        {
                            Id = 29,
                            PlanId = 12,
                            Status = 0,
                            UserId = "user-0009"
                        },
                        new
                        {
                            Id = 30,
                            PlanId = 12,
                            Status = 0,
                            UserId = "user-0010"
                        },
                        new
                        {
                            Id = 31,
                            PlanId = 13,
                            Status = 1,
                            UserId = "user-0006"
                        },
                        new
                        {
                            Id = 32,
                            PlanId = 13,
                            Status = 0,
                            UserId = "user-0007"
                        },
                        new
                        {
                            Id = 33,
                            PlanId = 14,
                            Status = 0,
                            UserId = "user-0008"
                        },
                        new
                        {
                            Id = 34,
                            PlanId = 14,
                            Status = 2,
                            UserId = "user-0009"
                        },
                        new
                        {
                            Id = 35,
                            PlanId = 15,
                            Status = 0,
                            UserId = "user-0010"
                        },
                        new
                        {
                            Id = 36,
                            PlanId = 15,
                            Status = 0,
                            UserId = "user-0006"
                        },
                        new
                        {
                            Id = 37,
                            PlanId = 12,
                            Status = 1,
                            UserId = "user-0007"
                        },
                        new
                        {
                            Id = 38,
                            PlanId = 13,
                            Status = 0,
                            UserId = "user-0008"
                        },
                        new
                        {
                            Id = 39,
                            PlanId = 9,
                            Status = 2,
                            UserId = "user-0009"
                        },
                        new
                        {
                            Id = 40,
                            PlanId = 9,
                            Status = 0,
                            UserId = "user-0010"
                        });
                });

            modelBuilder.Entity("ApiParchePlanU.Models.Parche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverImageUrl = "https://picsum.photos/seed/sistemas/400/200",
                            Description = "El parche de Ingeniería de Sistemas",
                            InviteCode = "SIS2026",
                            Name = "Parche Sistemas"
                        },
                        new
                        {
                            Id = 2,
                            CoverImageUrl = "https://picsum.photos/seed/industrial/400/200",
                            Description = "El parche de Ingeniería Industrial",
                            InviteCode = "IND2026",
                            Name = "Parche Industrial"
                        });
                });

            modelBuilder.Entity("ApiParchePlanU.Models.ParcheMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ParcheId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ParcheId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ParcheMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ParcheId = 1,
                            Role = 0,
                            UsuarioId = "user-0001"
                        },
                        new
                        {
                            Id = 2,
                            ParcheId = 1,
                            Role = 2,
                            UsuarioId = "user-0002"
                        },
                        new
                        {
                            Id = 3,
                            ParcheId = 1,
                            Role = 2,
                            UsuarioId = "user-0003"
                        },
                        new
                        {
                            Id = 4,
                            ParcheId = 1,
                            Role = 2,
                            UsuarioId = "user-0004"
                        },
                        new
                        {
                            Id = 5,
                            ParcheId = 1,
                            Role = 2,
                            UsuarioId = "user-0005"
                        },
                        new
                        {
                            Id = 6,
                            ParcheId = 2,
                            Role = 0,
                            UsuarioId = "user-0006"
                        },
                        new
                        {
                            Id = 7,
                            ParcheId = 2,
                            Role = 2,
                            UsuarioId = "user-0007"
                        },
                        new
                        {
                            Id = 8,
                            ParcheId = 2,
                            Role = 2,
                            UsuarioId = "user-0008"
                        },
                        new
                        {
                            Id = 9,
                            ParcheId = 2,
                            Role = 2,
                            UsuarioId = "user-0009"
                        },
                        new
                        {
                            Id = 10,
                            ParcheId = 2,
                            Role = 2,
                            UsuarioId = "user-0010"
                        });
                });

            modelBuilder.Entity("ApiParchePlanU.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndVoting")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParcheId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartVoting")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ParcheId");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatorId = "user-0001",
                            Description = "Plan de cine grupal",
                            EndVoting = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParcheId = 1,
                            StartVoting = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 1,
                            Title = "Cine en el campus"
                        },
                        new
                        {
                            Id = 2,
                            CreatorId = "user-0002",
                            Description = "Partido en la cancha",
                            EndVoting = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParcheId = 1,
                            StartVoting = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 1,
                            Title = "Partido de fútbol"
                        },
                        new
                        {
                            Id = 3,
                            CreatorId = "user-0001",
                            Description = "Almorzamos juntos",
                            EndVoting = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParcheId = 1,
                            StartVoting = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Title = "Almuerzo grupal"
                        },
                        new
                        {
                            Id = 4,
                            CreatorId = "user-0003",
                            Description = "Gaming night",
                            EndVoting = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParcheId = 1,
                            StartVoting = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 1,
                            Title = "Noche de videojuegos"
                        },
                        new
                        {
                            Id = 5,
                            CreatorId = "user-0002",
                            Description = "Cultura universitaria",
                            EndVoting = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParcheId = 1,
                            StartVoting = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 2,
                            Title = "Visita al museo"
                        },
                        new
                        {
                            Id = 6,
                            CreatorId = "user-0001",
                            Description = "Caminata por el cerro",
                            EndVoting = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParcheId = 1,
                            StartVoting = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 3,
                            Title = "Senderismo"
                        },
                        new
                        {
                            Id = 7,
                            CreatorId = "user-0004",
                            Description = "Música en vivo",
                            EndVoting = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParcheId = 1,
                            StartVoting = new DateTime(2026, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 1,
                            Title = "Concierto en el parque"
                        },
                        new
                        {
                            Id = 8,
                            CreatorId = "user-0005",
                            Description = "Preparación parciales",
                            EndVoting = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParcheId = 1,
                            StartVoting = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Title = "Estudio grupal"
                        },
                        new
                        {
                            Id = 9,
                            CreatorId = "user-0006",
                            Description = "Competencia interna",
                            EndVoting = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParcheId = 2,
                            StartVoting = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 1,
                            Title = "Torneo de ping pong"
                        },
                        new
                        {
                            Id = 10,
                            CreatorId = "user-0007",
                            Description = "Viaje de un día",
                            EndVoting = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParcheId = 2,
                            StartVoting = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 1,
                            Title = "Salida a Guatapé"
                        },
                        new
                        {
                            Id = 11,
                            CreatorId = "user-0006",
                            Description = "Asado grupal",
                            EndVoting = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParcheId = 2,
                            StartVoting = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 0,
                            Title = "BBQ en la finca"
                        },
                        new
                        {
                            Id = 12,
                            CreatorId = "user-0008",
                            Description = "Noche de karaoke",
                            EndVoting = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParcheId = 2,
                            StartVoting = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 2,
                            Title = "Karaoke"
                        },
                        new
                        {
                            Id = 13,
                            CreatorId = "user-0009",
                            Description = "Bowling universitario",
                            EndVoting = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParcheId = 2,
                            StartVoting = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 1,
                            Title = "Tarde de bowling"
                        },
                        new
                        {
                            Id = 14,
                            CreatorId = "user-0006",
                            Description = "Visita a la feria",
                            EndVoting = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParcheId = 2,
                            StartVoting = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 3,
                            Title = "Feria de emprendimiento"
                        },
                        new
                        {
                            Id = 15,
                            CreatorId = "user-0010",
                            Description = "Recorrido en bici",
                            EndVoting = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParcheId = 2,
                            StartVoting = new DateTime(2026, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 1,
                            Title = "Ciclovía grupal"
                        });
                });

            modelBuilder.Entity("ApiParchePlanU.Models.PlanOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Lugar = "Campus Universidad",
                            PlanId = 1,
                            Time = new DateTime(2026, 4, 5, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Lugar = "Parque El Poblado",
                            PlanId = 1,
                            Time = new DateTime(2026, 4, 6, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Lugar = "Centro Comercial",
                            PlanId = 1,
                            Time = new DateTime(2026, 4, 7, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Lugar = "Cancha Principal",
                            PlanId = 2,
                            Time = new DateTime(2026, 4, 5, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Lugar = "Cancha Secundaria",
                            PlanId = 2,
                            Time = new DateTime(2026, 4, 6, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Lugar = "Parque Deportivo",
                            PlanId = 2,
                            Time = new DateTime(2026, 4, 7, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Lugar = "Cafetería Central",
                            PlanId = 3,
                            Time = new DateTime(2026, 4, 5, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Lugar = "Restaurante Cerca",
                            PlanId = 3,
                            Time = new DateTime(2026, 4, 6, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Lugar = "Patio de Comidas",
                            PlanId = 3,
                            Time = new DateTime(2026, 4, 7, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Lugar = "Sala de Sistemas",
                            PlanId = 4,
                            Time = new DateTime(2026, 4, 5, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Lugar = "Apartamento",
                            PlanId = 4,
                            Time = new DateTime(2026, 4, 6, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Lugar = "Sala Comunal",
                            PlanId = 4,
                            Time = new DateTime(2026, 4, 7, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Lugar = "Museo de Antioquia",
                            PlanId = 5,
                            Time = new DateTime(2026, 4, 5, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Lugar = "Museo Arte Moderno",
                            PlanId = 5,
                            Time = new DateTime(2026, 4, 6, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Lugar = "Casa de la Cultura",
                            PlanId = 5,
                            Time = new DateTime(2026, 4, 7, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Lugar = "Cerro El Volador",
                            PlanId = 6,
                            Time = new DateTime(2026, 4, 5, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Lugar = "Cerro Nutibara",
                            PlanId = 6,
                            Time = new DateTime(2026, 4, 6, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Lugar = "Parque Arví",
                            PlanId = 6,
                            Time = new DateTime(2026, 4, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Lugar = "Parque Norte",
                            PlanId = 7,
                            Time = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Lugar = "Plaza Mayor",
                            PlanId = 7,
                            Time = new DateTime(2026, 4, 6, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            Lugar = "Teatro Metropolitano",
                            PlanId = 7,
                            Time = new DateTime(2026, 4, 7, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            Lugar = "Biblioteca Central",
                            PlanId = 8,
                            Time = new DateTime(2026, 4, 5, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            Lugar = "Sala de Estudio",
                            PlanId = 8,
                            Time = new DateTime(2026, 4, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            Lugar = "Aula Virtual",
                            PlanId = 8,
                            Time = new DateTime(2026, 4, 7, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            Lugar = "Sala de Juegos",
                            PlanId = 9,
                            Time = new DateTime(2026, 4, 5, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            Lugar = "Gimnasio",
                            PlanId = 9,
                            Time = new DateTime(2026, 4, 6, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            Lugar = "Patio Central",
                            PlanId = 9,
                            Time = new DateTime(2026, 4, 7, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            Lugar = "Guatapé Centro",
                            PlanId = 10,
                            Time = new DateTime(2026, 4, 5, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            Lugar = "La Piedra",
                            PlanId = 10,
                            Time = new DateTime(2026, 4, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            Lugar = "Embalse",
                            PlanId = 10,
                            Time = new DateTime(2026, 4, 7, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            Lugar = "Finca Privada",
                            PlanId = 11,
                            Time = new DateTime(2026, 4, 5, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            Lugar = "Parque Recreativo",
                            PlanId = 11,
                            Time = new DateTime(2026, 4, 6, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            Lugar = "Club Campestre",
                            PlanId = 11,
                            Time = new DateTime(2026, 4, 7, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            Lugar = "Bar Karaoke Centro",
                            PlanId = 12,
                            Time = new DateTime(2026, 4, 5, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            Lugar = "Restaurante Bar",
                            PlanId = 12,
                            Time = new DateTime(2026, 4, 6, 21, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            Lugar = "Terraza Laureles",
                            PlanId = 12,
                            Time = new DateTime(2026, 4, 7, 22, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            Lugar = "Bolera El Tesoro",
                            PlanId = 13,
                            Time = new DateTime(2026, 4, 5, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            Lugar = "Bolera Unicentro",
                            PlanId = 13,
                            Time = new DateTime(2026, 4, 6, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            Lugar = "Bolera Mayorca",
                            PlanId = 13,
                            Time = new DateTime(2026, 4, 7, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            Lugar = "Plaza de Ferias",
                            PlanId = 14,
                            Time = new DateTime(2026, 4, 5, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            Lugar = "Centro de Eventos",
                            PlanId = 14,
                            Time = new DateTime(2026, 4, 6, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            Lugar = "Pabellón Expo",
                            PlanId = 14,
                            Time = new DateTime(2026, 4, 7, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            Lugar = "Ciclovía Avenida",
                            PlanId = 15,
                            Time = new DateTime(2026, 4, 5, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            Lugar = "Parque Lineal",
                            PlanId = 15,
                            Time = new DateTime(2026, 4, 6, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            Lugar = "Ruta Montaña",
                            PlanId = 15,
                            Time = new DateTime(2026, 4, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ApiParchePlanU.Models.Ranking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GhosScore")
                        .HasColumnType("int");

                    b.Property<int>("OrganizerScore")
                        .HasColumnType("int");

                    b.Property<int>("ParcheId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rankings");
                });

            modelBuilder.Entity("ApiParchePlanU.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Programa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user-0001",
                            AccessFailedCount = 0,
                            AvatarUrl = "https://i.pravatar.cc/150?img=1",
                            ConcurrencyStamp = "61634e69-3f9c-4075-875b-7a55482f2e1e",
                            Email = "miguelg@universidad.edu.co",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NombreCompleto = "Miguel Gomez",
                            NormalizedEmail = "MIGUELG@UNIVERSIDAD.EDU.CO",
                            NormalizedUserName = "MIGUELG",
                            PasswordHash = "AQAAAAIAAYagAAAAEP52pK7DjOO3RRlghXyWLLccWFImunrp5ujtLWHMCg29f+DoSb4U81DUEtxBBdrSBw==",
                            PhoneNumberConfirmed = false,
                            Programa = "Ingeniería de Sistemas",
                            SecurityStamp = "30ca33c5-c48b-4aaf-907f-77242167fcc8",
                            TwoFactorEnabled = false,
                            UserName = "miguelg"
                        },
                        new
                        {
                            Id = "user-0002",
                            AccessFailedCount = 0,
                            AvatarUrl = "https://i.pravatar.cc/150?img=2",
                            ConcurrencyStamp = "8f9a692c-b4ec-4de9-aebe-25867f8aea6d",
                            Email = "andresb@universidad.edu.co",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NombreCompleto = "Andres Baena",
                            NormalizedEmail = "ANDRESB@UNIVERSIDAD.EDU.CO",
                            NormalizedUserName = "ANDRESB",
                            PasswordHash = "AQAAAAIAAYagAAAAEP52pK7DjOO3RRlghXyWLLccWFImunrp5ujtLWHMCg29f+DoSb4U81DUEtxBBdrSBw==",
                            PhoneNumberConfirmed = false,
                            Programa = "Ingeniería de Sistemas",
                            SecurityStamp = "367db611-ae51-41a1-94d9-6e7e7d2202d5",
                            TwoFactorEnabled = false,
                            UserName = "andresb"
                        },
                        new
                        {
                            Id = "user-0003",
                            AccessFailedCount = 0,
                            AvatarUrl = "https://i.pravatar.cc/150?img=3",
                            ConcurrencyStamp = "179a6ae6-090c-4eaa-aaaf-c5416a25d5ad",
                            Email = "laurart@universidad.edu.co",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NombreCompleto = "Laura Torres",
                            NormalizedEmail = "LAURART@UNIVERSIDAD.EDU.CO",
                            NormalizedUserName = "LAURART",
                            PasswordHash = "AQAAAAIAAYagAAAAEP52pK7DjOO3RRlghXyWLLccWFImunrp5ujtLWHMCg29f+DoSb4U81DUEtxBBdrSBw==",
                            PhoneNumberConfirmed = false,
                            Programa = "Ingeniería de Sistemas",
                            SecurityStamp = "8dc48d0d-d19a-4a66-9da1-61ca5aed055b",
                            TwoFactorEnabled = false,
                            UserName = "laurart"
                        },
                        new
                        {
                            Id = "user-0004",
                            AccessFailedCount = 0,
                            AvatarUrl = "https://i.pravatar.cc/150?img=4",
                            ConcurrencyStamp = "4205eca5-da19-41df-aea3-318c07e39933",
                            Email = "carlosr@universidad.edu.co",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NombreCompleto = "Carlos Ruiz",
                            NormalizedEmail = "CARLOSR@UNIVERSIDAD.EDU.CO",
                            NormalizedUserName = "CARLOSR",
                            PasswordHash = "AQAAAAIAAYagAAAAEP52pK7DjOO3RRlghXyWLLccWFImunrp5ujtLWHMCg29f+DoSb4U81DUEtxBBdrSBw==",
                            PhoneNumberConfirmed = false,
                            Programa = "Ingeniería de Sistemas",
                            SecurityStamp = "8806076c-a4ca-49a8-9ae6-11e7729d1bb2",
                            TwoFactorEnabled = false,
                            UserName = "carlosr"
                        },
                        new
                        {
                            Id = "user-0005",
                            AccessFailedCount = 0,
                            AvatarUrl = "https://i.pravatar.cc/150?img=5",
                            ConcurrencyStamp = "8018adb7-b911-4ba1-a68d-fcda5205d3d5",
                            Email = "marial@universidad.edu.co",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NombreCompleto = "Maria Lopez",
                            NormalizedEmail = "MARIAL@UNIVERSIDAD.EDU.CO",
                            NormalizedUserName = "MARIAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEP52pK7DjOO3RRlghXyWLLccWFImunrp5ujtLWHMCg29f+DoSb4U81DUEtxBBdrSBw==",
                            PhoneNumberConfirmed = false,
                            Programa = "Ingeniería de Sistemas",
                            SecurityStamp = "66b94545-523a-4fc5-a9a0-3b443805e164",
                            TwoFactorEnabled = false,
                            UserName = "marial"
                        },
                        new
                        {
                            Id = "user-0006",
                            AccessFailedCount = 0,
                            AvatarUrl = "https://i.pravatar.cc/150?img=6",
                            ConcurrencyStamp = "c65efef9-82a4-45b3-8608-e35551046328",
                            Email = "juanp@universidad.edu.co",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NombreCompleto = "Juan Perez",
                            NormalizedEmail = "JUANP@UNIVERSIDAD.EDU.CO",
                            NormalizedUserName = "JUANP",
                            PasswordHash = "AQAAAAIAAYagAAAAEP52pK7DjOO3RRlghXyWLLccWFImunrp5ujtLWHMCg29f+DoSb4U81DUEtxBBdrSBw==",
                            PhoneNumberConfirmed = false,
                            Programa = "Ingeniería Industrial",
                            SecurityStamp = "0e8bc488-76ff-444d-9324-935cb2dfe66e",
                            TwoFactorEnabled = false,
                            UserName = "juanp"
                        },
                        new
                        {
                            Id = "user-0007",
                            AccessFailedCount = 0,
                            AvatarUrl = "https://i.pravatar.cc/150?img=7",
                            ConcurrencyStamp = "761652e4-be86-4ac1-8285-37ecc10079a7",
                            Email = "sofiad@universidad.edu.co",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NombreCompleto = "Sofia Diaz",
                            NormalizedEmail = "SOFIAD@UNIVERSIDAD.EDU.CO",
                            NormalizedUserName = "SOFIAD",
                            PasswordHash = "AQAAAAIAAYagAAAAEP52pK7DjOO3RRlghXyWLLccWFImunrp5ujtLWHMCg29f+DoSb4U81DUEtxBBdrSBw==",
                            PhoneNumberConfirmed = false,
                            Programa = "Ingeniería Industrial",
                            SecurityStamp = "1f78e631-07f5-40f6-9275-4dadaecfbe3d",
                            TwoFactorEnabled = false,
                            UserName = "sofiad"
                        },
                        new
                        {
                            Id = "user-0008",
                            AccessFailedCount = 0,
                            AvatarUrl = "https://i.pravatar.cc/150?img=8",
                            ConcurrencyStamp = "6dbbe494-db38-4d2a-a8b5-b567c2f33628",
                            Email = "danielc@universidad.edu.co",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NombreCompleto = "Daniel Castro",
                            NormalizedEmail = "DANIELC@UNIVERSIDAD.EDU.CO",
                            NormalizedUserName = "DANIELC",
                            PasswordHash = "AQAAAAIAAYagAAAAEP52pK7DjOO3RRlghXyWLLccWFImunrp5ujtLWHMCg29f+DoSb4U81DUEtxBBdrSBw==",
                            PhoneNumberConfirmed = false,
                            Programa = "Ingeniería Industrial",
                            SecurityStamp = "d091456a-0947-49b8-a9dc-41c5aaacf729",
                            TwoFactorEnabled = false,
                            UserName = "danielc"
                        },
                        new
                        {
                            Id = "user-0009",
                            AccessFailedCount = 0,
                            AvatarUrl = "https://i.pravatar.cc/150?img=9",
                            ConcurrencyStamp = "e63dc1bb-d514-43ef-a139-903973d60f50",
                            Email = "valentinag@universidad.edu.co",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NombreCompleto = "Valentina Gil",
                            NormalizedEmail = "VALENTINAG@UNIVERSIDAD.EDU.CO",
                            NormalizedUserName = "VALENTINAG",
                            PasswordHash = "AQAAAAIAAYagAAAAEP52pK7DjOO3RRlghXyWLLccWFImunrp5ujtLWHMCg29f+DoSb4U81DUEtxBBdrSBw==",
                            PhoneNumberConfirmed = false,
                            Programa = "Ingeniería Industrial",
                            SecurityStamp = "4a369671-4a9f-4bba-a7e3-246a705c897a",
                            TwoFactorEnabled = false,
                            UserName = "valentinag"
                        },
                        new
                        {
                            Id = "user-0010",
                            AccessFailedCount = 0,
                            AvatarUrl = "https://i.pravatar.cc/150?img=10",
                            ConcurrencyStamp = "aa091e8a-2801-4389-b3bf-017b1e2be22b",
                            Email = "camilov@universidad.edu.co",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NombreCompleto = "Camilo Vargas",
                            NormalizedEmail = "CAMILOV@UNIVERSIDAD.EDU.CO",
                            NormalizedUserName = "CAMILOV",
                            PasswordHash = "AQAAAAIAAYagAAAAEP52pK7DjOO3RRlghXyWLLccWFImunrp5ujtLWHMCg29f+DoSb4U81DUEtxBBdrSBw==",
                            PhoneNumberConfirmed = false,
                            Programa = "Ingeniería Industrial",
                            SecurityStamp = "15e5556f-ccc4-4a18-a4f8-c8955890d576",
                            TwoFactorEnabled = false,
                            UserName = "camilov"
                        });
                });

            modelBuilder.Entity("ApiParchePlanU.Models.Vote", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("PlanOptionId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PlanId");

                    b.HasIndex("PlanId");

                    b.HasIndex("PlanOptionId");

                    b.ToTable("Votes");

                    b.HasData(
                        new
                        {
                            UserId = "user-0001",
                            PlanId = 1,
                            PlanOptionId = 1
                        },
                        new
                        {
                            UserId = "user-0002",
                            PlanId = 1,
                            PlanOptionId = 2
                        },
                        new
                        {
                            UserId = "user-0002",
                            PlanId = 2,
                            PlanOptionId = 4
                        },
                        new
                        {
                            UserId = "user-0003",
                            PlanId = 2,
                            PlanOptionId = 5
                        },
                        new
                        {
                            UserId = "user-0003",
                            PlanId = 3,
                            PlanOptionId = 7
                        },
                        new
                        {
                            UserId = "user-0004",
                            PlanId = 3,
                            PlanOptionId = 8
                        },
                        new
                        {
                            UserId = "user-0004",
                            PlanId = 4,
                            PlanOptionId = 10
                        },
                        new
                        {
                            UserId = "user-0005",
                            PlanId = 4,
                            PlanOptionId = 11
                        },
                        new
                        {
                            UserId = "user-0005",
                            PlanId = 5,
                            PlanOptionId = 13
                        },
                        new
                        {
                            UserId = "user-0001",
                            PlanId = 5,
                            PlanOptionId = 14
                        },
                        new
                        {
                            UserId = "user-0001",
                            PlanId = 6,
                            PlanOptionId = 16
                        },
                        new
                        {
                            UserId = "user-0002",
                            PlanId = 6,
                            PlanOptionId = 17
                        },
                        new
                        {
                            UserId = "user-0003",
                            PlanId = 7,
                            PlanOptionId = 19
                        },
                        new
                        {
                            UserId = "user-0004",
                            PlanId = 7,
                            PlanOptionId = 20
                        },
                        new
                        {
                            UserId = "user-0005",
                            PlanId = 8,
                            PlanOptionId = 22
                        },
                        new
                        {
                            UserId = "user-0006",
                            PlanId = 9,
                            PlanOptionId = 25
                        },
                        new
                        {
                            UserId = "user-0007",
                            PlanId = 9,
                            PlanOptionId = 26
                        },
                        new
                        {
                            UserId = "user-0007",
                            PlanId = 10,
                            PlanOptionId = 28
                        },
                        new
                        {
                            UserId = "user-0008",
                            PlanId = 10,
                            PlanOptionId = 29
                        },
                        new
                        {
                            UserId = "user-0008",
                            PlanId = 11,
                            PlanOptionId = 31
                        },
                        new
                        {
                            UserId = "user-0009",
                            PlanId = 11,
                            PlanOptionId = 32
                        },
                        new
                        {
                            UserId = "user-0009",
                            PlanId = 12,
                            PlanOptionId = 34
                        },
                        new
                        {
                            UserId = "user-0010",
                            PlanId = 12,
                            PlanOptionId = 35
                        },
                        new
                        {
                            UserId = "user-0010",
                            PlanId = 13,
                            PlanOptionId = 37
                        },
                        new
                        {
                            UserId = "user-0006",
                            PlanId = 13,
                            PlanOptionId = 38
                        },
                        new
                        {
                            UserId = "user-0006",
                            PlanId = 14,
                            PlanOptionId = 40
                        },
                        new
                        {
                            UserId = "user-0007",
                            PlanId = 14,
                            PlanOptionId = 41
                        },
                        new
                        {
                            UserId = "user-0007",
                            PlanId = 15,
                            PlanOptionId = 43
                        },
                        new
                        {
                            UserId = "user-0008",
                            PlanId = 15,
                            PlanOptionId = 44
                        },
                        new
                        {
                            UserId = "user-0009",
                            PlanId = 8,
                            PlanOptionId = 23
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1b2c3d4-0001-0001-0001-000000000001",
                            ConcurrencyStamp = "c0dee45e-8fd0-40b2-ba22-9c27619191e0",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "a1b2c3d4-0001-0001-0001-000000000002",
                            ConcurrencyStamp = "55dc4945-d184-4a7b-8e52-41fc7c3091da",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ApiParchePlanU.Models.Attendance", b =>
                {
                    b.HasOne("ApiParchePlanU.Models.Plan", "plan")
                        .WithMany("Attendances")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiParchePlanU.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("plan");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ApiParchePlanU.Models.ParcheMember", b =>
                {
                    b.HasOne("ApiParchePlanU.Models.Parche", "parche")
                        .WithMany("Members")
                        .HasForeignKey("ParcheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiParchePlanU.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("parche");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ApiParchePlanU.Models.Plan", b =>
                {
                    b.HasOne("ApiParchePlanU.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ApiParchePlanU.Models.Parche", "parche")
                        .WithMany("Plans")
                        .HasForeignKey("ParcheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("parche");
                });

            modelBuilder.Entity("ApiParchePlanU.Models.PlanOption", b =>
                {
                    b.HasOne("ApiParchePlanU.Models.Plan", "plan")
                        .WithMany("Options")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("plan");
                });

            modelBuilder.Entity("ApiParchePlanU.Models.Vote", b =>
                {
                    b.HasOne("ApiParchePlanU.Models.Plan", "plan")
                        .WithMany("Votes")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ApiParchePlanU.Models.PlanOption", "PlanOption")
                        .WithMany("Votes")
                        .HasForeignKey("PlanOptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ApiParchePlanU.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PlanOption");

                    b.Navigation("plan");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApiParchePlanU.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApiParchePlanU.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiParchePlanU.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApiParchePlanU.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiParchePlanU.Models.Parche", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Plans");
                });

            modelBuilder.Entity("ApiParchePlanU.Models.Plan", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Options");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("ApiParchePlanU.Models.PlanOption", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
